name: Terraform Apply
description: Apply Terraform from a specified working directory with JSON variable support

inputs:
  working-directory:
    description: The working directory containing Terraform configuration
    required: true
    default: .

  variables-json:
    description: JSON string containing variables to set as TF_VAR_* environment variables
    required: false
    default: '{}'

runs:
  using: composite
  steps:
    - name: Set TF_VAR environment variables from JSON
      shell: bash
      run: |
        set -e

        # Parse JSON and set environment variables
        json_input='${{ inputs.variables-json }}'

        if [ -z "$json_input" ] || [ "$json_input" = '{}' ]; then
          echo "No variables provided"
        else
          # Use jq to iterate through JSON keys and set TF_VAR_* variables
          echo "$json_input" | jq -r 'to_entries[] | "TF_VAR_\(.key)=\(.value)"' | while read -r var; do
            echo "Setting $var"
            echo "$var" >> $GITHUB_ENV
          done
        fi

    - name: Terraform Init
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: terraform init

    # - name: Terraform Plan
    #   shell: bash
    #   working-directory: ${{ inputs.working-directory }}
    #   run: terraform plan -out=tfplan

    - name: Terraform Apply
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: terraform apply -auto-approve
