name: Terraform Apply
description: Apply Terraform from a specified working directory with JSON variable support

inputs:
  working-directory:
    description: The working directory containing Terraform configuration
    required: true
    default: .

  # variables:
  #   description: Content for Terraform variable files
  #   required: true
  #   default: ''

runs:
  using: composite
  steps:
    # - name: Create terraform.tfvars with inputs
    #   working-directory: ${{ inputs.working-directory }}
    #   shell: bash
    #   run: |
    #     FILE_CONTENT="${{ inputs.variables }}"
    #     cat <<EOF > terraform.tfvars
    #     $FILE_CONTENT
    #     EOF

    - name: Terraform Init
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: terraform init

    - name: Terraform Plan
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: terraform apply -auto-approve tfplan
