name: Create release
description:

inputs:
  tag:
    description: The git tag to use for the release
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Create release
      id: create-version
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.GITHUB_TOKEN }}
        TAG: ${{ inputs.tag }}
      run: |
          gh release create "${TAG}" --repo "${GITHUB_REPOSITORY}" --title "${TAG}" --generate-notes"