name: Scaffold New Repository
description: 'Scaffolds a new repository with Terraform configuration to create the repository'

inputs:
  repository:
    description: 'Name for the new repository (name only)'
    required: true
    type: string
  token:
    description: 'GitHub Token with repo and workflow permissions'
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    - name: Apply Terraform to Scaffold Repository
      uses: ./.github/actions/terraform-apply
      with:
        working-directory: ./.github/actions/scaffold-repository/terraform
        variables-json: |
          {
            "repository_name": "${{ inputs.repository }}",
            "github_token": "${{ inputs.token }}"
          }
