name: 'Terraform AWS'
description: 'Apply Terraform configurations to AWS with automatic backend configuration'

inputs:
  working-directory:
    description: 'The working directory containing Terraform configuration'
    required: true
    default: '.'
  aws-region:
    description: 'AWS region to target'
    required: false
    default: 'us-east-1'
  terraform-version:
    description: 'Terraform version to use'
    required: false
    default: '1.5.0'
  backend-config:
    description: 'Backend configuration as JSON'
    required: false

runs:
  using: 'composite'
  steps:
    - name: 'Setup Terraform'
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform-version }}

    - name: 'Configure AWS credentials'
      shell: bash
      env:
        AWS_REGION: ${{ inputs.aws-region }}
      run: |
        echo "AWS Region configured: $AWS_REGION"

    - name: 'Terraform Init'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        AWS_REGION: ${{ inputs.aws-region }}
      run: |
        terraform init -upgrade
        if [ -n "${{ inputs.backend-config }}" ]; then
          echo "Applying backend configuration..."
          echo "${{ inputs.backend-config }}" | jq .
        fi

    - name: 'Terraform Validate'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: terraform validate

    - name: 'Terraform Plan'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        AWS_REGION: ${{ inputs.aws-region }}
      run: terraform plan -out=tfplan

    - name: 'Terraform Apply'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        AWS_REGION: ${{ inputs.aws-region }}
      run: terraform apply -auto-approve tfplan
