name: Continuous Integration

on:
  push:

jobs:
  unit-test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Run tests
          run: |
            echo "Running unit tests..."
            # Add your test commands here, e.g., npm test, pytest, etc.

  stage-two:
    runs-on: ubuntu-latest
    needs: print-env-variable
    environment: ${{ inputs.environment }}
    steps:
      - name: Print custom message
        run: |
          echo "Message: ${{ inputs.message }}"

      - name: Print environment variable
        run: |
          echo "Environment variable example: ${{ vars.ENV_VAR || 'No ENV_VAR set' }}"

      - name: Print all available context
        run: |
          echo "GitHub Environment: ${{ github.environment }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Repository: ${{ github.repository }}"
  stage-three:
    runs-on: ubuntu-latest
    needs: stage-two
    environment: production
    steps:
      - name: Print custom message
        run: |
          echo "Message: ${{ inputs.message }}"

      - name: Print environment name
        run: |
          echo "Environment: ${{ vars.ENVIRONMENT || 'development' }}"

      - name: Print environment variable
        run: |
          echo "Environment variable example: ${{ vars.ENV_VAR || 'No ENV_VAR set' }}"

      - name: Print all available context
        run: |
          echo "GitHub Environment: ${{ github.environment }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Repository: ${{ github.repository }}"

  stage-four:
    runs-on: ubuntu-latest
    needs: print-env-variable
    environment: template
    steps:
      - name: Print custom message
        run: |
          echo "Message: ${{ inputs.message }}"

      - name: Print environment name
        run: |
          echo "Environment: ${{ vars.ENVIRONMENT || 'development' }}"

      - name: Print environment variable
        run: |
          echo "Environment variable example: ${{ vars.ENV_VAR || 'No ENV_VAR set' }}"

      - name: Print all available context
        run: |
            echo "GitHub Environment: ${{ github.environment }}"
            echo "Workflow: ${{ github.workflow }}"
            echo "Repository: ${{ github.repository }}"
            echo "Runnumber: ${{ github.run_number }}"
            echo "RunID: ${{ github.run_id }}"
            echo "Actor: ${{ github.actor }}"
            echo "SHA: ${{ github.sha }}"
